### PR TITLE
Add HHelmet to HDest Addons Menu

### PR DESCRIPTION
**Pull request by UndeadZeratul**

### CODE REVIEW

**Comment by dastrukar** [comment]
Could you remove it from the HD Options menu?
I don't think it would make sense to have it there since the addons menu is in the same place.

**Comment by UndeadZeratul** [comment]
Oh, sure!  I've just seen other mods keep it in both, but yeah I can remove the normal menu too

**Comment by dastrukar** [comment]
Wait hold on, i think you removed it from the `Options` menu, not the `HD Options` menu

**Comment by UndeadZeratul** [comment]
Oh, whoops!  my bad.  Hang on.

**Comment by dastrukar** [comment]
Alright, seems to be good now.

**Pull request merged**
